spring.datasource.url=jdbc:mysql://localhost:3306/springproject?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Sai@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
server.session.tracking-modes=cookie
app.jwt-secret=2Can8GzVu8K389XITD5ny3dqKWzVhp2/HQrxySLJIMs=
app-jwt-expiration-milliseconds=604800000